global:
  end_year: 2016
  start_year: 2021
simulate:
  checkpoint_path: networks/new_collect_test_2
  use_epoch: 100
  use_max_prob: true
  use_removed_players: true
train:
  auto_set_ckpt: true
  epochs: 1000
  name: new_collect_test_2
  use_timestamp: false
  validation_percent: 30
visual:
  results_path: max_0114_2022-03-11 095111.331105
  use_true_results: false
