global:
  end_year: 2016
  start_year: 2021
simulate:
  checkpoint_path: networks/2022-02-12 114632.419977.ckpt
  use_removed_players: true
train:
  activation_function: relu
  auto_set_ckpt: true
  epochs: 25
  validation_percent: 30
visual:
  use_true_results: False
