global:
  end_year: 2016
  start_year: 2021
simulate:
  checkpoint_path: networks/2022-02-16 092300.321909.ckpt
  use_removed_players: true
  use_max_prob: false
train:
  auto_set_ckpt: true
  epochs: 50
  validation_percent: 30
visual:
  use_true_results: false
