global:
  end_year: 2016
  start_year: 2021
simulate:
  checkpoint_path: networks/2022-02-12 113620.268569.ckpt
train:
  activation_function: relu
  auto_set_ckpt: true
  epochs: 25
  validation_percent: 30
