global:
  check_results: true
  end_year: 2018
  start_year: 2021
simulate:
  checkpoint_path: 
  lpf_score: 0
  lpf_simulate: 0.2
  use_epoch: 102
  use_max_prob: false
  use_removed_players: true
train:
  auto_set_ckpt: true
  epochs: 1000
  name: example
  use_timestamp: false
  validation_percent: 30
visual:
  results_path: 
